######################################################################
##
## Filename: ALU.udo
## Created on: Fri Dec 02 13:52:47 东部标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
