######################################################################
##
## Filename: CPU.udo
## Created on: Fri Dec 02 14:38:38 东部标准时间 2016
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
